import turtle
a=turtle.Turtle()
a.speed(0)
a.pu()
a.sety(-125)
a.pencolor("#c20907")
a.begin_fill()
a.color("#c20907")
for i in range(2):
    a.fd(500)
    a.lt(90)
    a.fd(25)
    a.lt(90)
    a.pd()
a.end_fill()
a.pu()
a.sety(-100)
a.pencolor("white")
a.begin_fill()
a.color("white")
for i in range(2):
    a.fd(500)
    a.lt(90)
    a.fd(25)
    a.lt(90)
    a.pd()
a.end_fill()
a.pu()
a.sety(-75)
a.pencolor("#c20907")
a.begin_fill()
a.color("#c20907")
for i in range(2):
    a.fd(500)
    a.lt(90)
    a.fd(25)
    a.lt(90)
    a.pd()
a.end_fill()
a.pu()
a.sety(-50)
a.pencolor("white")
a.begin_fill()
a.color("white")
for i in range(2):
    a.fd(500)
    a.lt(90)
    a.fd(25)
    a.lt(90)
    a.pd()
a.end_fill()
a.pu()
a.sety(-25)
a.pencolor("#c20907")
a.begin_fill()
a.color("#c20907")
for i in range(2):
    a.fd(500)
    a.lt(90)
    a.fd(25)
    a.lt(90)
    a.pd()
a.end_fill()    
a.pu()
a.sety(0)
a.pencolor("white")
a.begin_fill()
a.color("white")
for i in range(2):
    a.fd(500)
    a.lt(90)
    a.fd(25)
    a.lt(90)
    a.pd()
a.end_fill()    
a.pu()
a.sety(25)
a.pencolor("#c20907")
a.begin_fill()
a.color("#c20907")
for i in range(2):
    a.fd(500)
    a.lt(90)
    a.fd(25)
    a.lt(90)
    a.pd()
a.end_fill()
a.pu()
a.pu()
a.sety(50)
a.pencolor("white")
a.begin_fill()
a.color("white")
for i in range(2):
    a.fd(500)
    a.lt(90)
    a.fd(25)
    a.lt(90)
    a.pd()
a.end_fill()
a.pu()
a.sety(75)
a.pencolor("#c20907")
a.begin_fill()
a.color("#c20907")
for i in range(2):
    a.fd(500)
    a.lt(90)
    a.fd(25)
    a.lt(90)
    a.pd()
a.end_fill()
a.pu()
a.sety(100)
a.pencolor("white")
a.begin_fill()
a.color("white")
for i in range(2):
    a.fd(500)
    a.lt(90)
    a.fd(25)
    a.lt(90)
    a.pd()
a.end_fill()
a.pu()
a.sety(125)
a.pencolor("#c20907")
a.begin_fill()
a.color("#c20907")
for i in range(2):
    a.fd(500)
    a.lt(90)
    a.fd(25)
    a.lt(90)
    a.pd()
a.end_fill()
a.pu()
a.sety(150)
a.pencolor("white")
a.begin_fill()
a.color("white")
for i in range(2):
    a.fd(500)
    a.lt(90)
    a.fd(25)
    a.lt(90)
    a.pd()
a.end_fill()
a.pu()
a.sety(175)
a.pencolor("#c20907")
a.begin_fill()
a.color("#c20907")
for i in range(2):
    a.fd(500)
    a.lt(90)
    a.fd(25)
    a.lt(90)
    a.pd()
a.end_fill()
a.pu()
a.home()
a.sety(25)
a.begin_fill()
a.color("#050a97")
for i in range(2):
    a.fd(200)
    a.lt(90)
    a.fd(175)
    a.lt(90)
    a.pd()
a.end_fill()
a.pd()
a.pu()
a.pu()
a.goto(15,185)
a.begin_fill()
a.color("white")
a.pd()
for i in range(6):
    a.pencolor("white")
    for i in range(5):
      a.forward(10)
      a.right(144)   
    a.pu()
    a.forward(30)
    a.pd()
a.end_fill() 
a.pu()
a.goto(30,165)
a.pd()
a.begin_fill()
a.color("white")
for i in range(5):
   for i in range(5):
      a.forward(10)
      a.right(144)    
   a.pu()
   a.forward(30)
   a.pd()
a.end_fill()    
a.pu()
a.goto(15,145)
a.pd()
a.begin_fill()
a.color("white")
for i in range(6):
   for i in range(5):
      a.forward(10)
      a.right(144)    
   a.pu()
   a.forward(30)
   a.pd()
a.end_fill()    
a.pu()
a.goto(30,125)
a.pd()
a.begin_fill()
a.color("white")
for i in range(5):
   for i in range(5):
      a.forward(10)
      a.right(144)    
   a.pu()
   a.forward(30)
   a.pd()
a.end_fill()    
a.pu()
a.goto(15,105)
a.pd()
a.begin_fill()
a.color("white")
for i in range(6):
   for i in range(5):
      a.forward(10)
      a.right(144)    
   a.pu()
   a.forward(30)
   a.pd()
a.end_fill()    
a.pu()
a.goto(30,90)
a.pd()
a.begin_fill()
a.color("white")
for i in range(5):
   for i in range(5):
      a.forward(10)
      a.right(144)
   a.pu()
   a.forward(30)
   a.pd()   
a.end_fill() 
a.pu()
a.goto(15,75)
a.pd()
a.begin_fill()
a.color("white")
for i in range(6):
   for i in range(5):
      a.forward(10)
      a.right(144)
   a.pu()
   a.forward(30)
   a.pd()
a.end_fill()      
a.pu()
a.goto(30,60)
a.pd()
a.begin_fill()
a.color("white")
for i in range(5):
   for i in range(5):
      a.forward(10)
      a.right(144)
   a.pu()
   a.forward(30)
   a.pd()
a.end_fill() 
a.pu()
a.goto(15,45)
a.pd()
a.begin_fill()
a.color("white")
for i in range(6):
   for i in range(5):
      a.forward(10)
      a.right(144)
   a.pu()
   a.forward(30)
   a.pd()
a.end_fill()
a.pu()
a.home()



















