import turtle

a = turtle.Turtle()

a.speed(0)

for i in range(3):
    a.pu()

    a.goto(-13,110)
    a.pensize(3)
    a.pencolor("green")
    a.begin_fill()
    a.pd()
    a.fd(30)
    a.rt(90)
    a.fd(50)
    a.rt(90)
    a.fd(30)
    a.rt(90)
    a.fd(30)
    a.rt(90)
    a.color("green")
    a.end_fill()
    a.pu()
    
    a.goto(-43,60)
    a.pensize(3)
    a.pencolor("green")
    a.begin_fill()
    a.pd()
    a.fd(90)
    a.rt(90)
    a.fd(130)
    a.rt(90)
    a.fd(90)
    a.rt(90)
    a.fd(90)
    a.rt(90)
    a.color("green")
    a.end_fill()
    a.pd()
    a.pu()

    a.goto(0,90)
    a.pd()
    a.pensize(3)    
    a.pencolor("yellow")
    a.begin_fill()
    a.circle(70,360)
    a.color("yellow")
    a.end_fill()
    a.pu()
    
    a.goto(-30,170)
    a.dot(20,"brown")
    a.pd()
    a.pu()
        
    a.goto(30,170)
    a.dot(20,"brown")
    a.pd()
    a.pu()
        
    a.goto(0,155)
    a.dot(13,"brown")
    a.pd()
    a.pu()
        
    a.goto(-30,170)
    a.dot(12,"pink")
    a.pd()
    a.pu()

    a.goto(30,170)
    a.dot(12,"pink")
    a.pd()
    a.pu()
         
    a.goto(-7,120)
    a.pensize(1)
    a.pencolor("brown")
    a.begin_fill()
    a.pd()
    a.fd(20)
    a.rt(90)
    a.fd(5)
    a.rt(90)
    a.fd(20)
    a.rt(90)
    a.fd(5)
    a.rt(90)
    a.color("brown")
    a.end_fill()
    a.pd()
    a.pu()
        
    a.goto(-125,55)
    a.pensize(3)
    a.pencolor("blue")
    a.begin_fill()
    a.pd()
    a.fd(80)
    a.rt(90)
    a.fd(30)
    a.rt(90)
    a.fd(80)
    a.rt(90)
    a.fd(30)
    a.rt(90)
    a.color("blue")
    a.end_fill()
    a.pd()
    a.pu()
        
    a.goto(50,55)
    a.pensize(3)
    a.pencolor("blue")
    a.begin_fill()
    a.pd()
    a.fd(80)
    a.rt(90)
    a.fd(30)
    a.rt(90)
    a.fd(80)
    a.rt(90)
    a.fd(30)
    a.rt(90)
    a.color("blue")
    a.end_fill()
    a.pd()
    a.pu()

    a.goto(-36,-73)
    a.pensize(3)
    a.pencolor("blue")
    a.begin_fill()
    a.pd()
    a.fd(20)
    a.rt(90)
    a.fd(100)
    a.rt(90)
    a.fd(20)
    a.rt(90)
    a.fd(20)
    a.rt(90)
    a.color("blue")
    a.end_fill()
    a.pd()
    a.pu()
        
    a.goto(22,-73)
    a.pensize(3)
    a.pencolor("blue")
    a.begin_fill()
    a.pd()
    a.fd(20)
    a.rt(90)
    a.fd(100)
    a.rt(90)
    a.fd(20)
    a.rt(90)
    a.fd(20)
    a.rt(90)
    a.color("blue")
    a.end_fill()
    a.pd()

    a.pu()
    a.fd(100)
    a.pd()
    


    
